### PR TITLE
Simplify and speedup docker images

### PR DESCRIPTION
**Pull request by sanekto**
This PR makes the docker image creation faster and simpler.
The bots now share the same docker image, to select with bot to run use the BOT_NAME env variable:

Options are:

* `BOT_NAME=bridge_keeper`
* `BOT_NAME=EURe_rebalancing`
* `BOT_NAME=spark_anti_liquidation`

This change obvously impacts in the deployment of the bots so @dharmendrakariya please take that into account.

### CODE REVIEW

**Comment by dharmendrakariya** [comment]
This looks awesome! I like this approach! I am gonna deploy the images from this branch and then let you know if it runs perfectly fine or not! then we can merge it!

**Comment by spiccinini** [comment]
Great! Thanks @dharmendrakariya . Also there is something else I changed in the Dockerfile that you may like, now there is no need to install gcc as I built the whl for the "problematic" safe_pysha3 package and put it in a repo. Tell me what do you think about it (or if you prefer the other way building the package locally).

**Comment by dharmendrakariya** [comment]
@sanekto @sgzerbo  I have tested and its working fine! we can merge this!

**Review by dharmendrakariya — APPROVED** [review]

**Comment by dharmendrakariya** [comment]
> Great! Thanks @dharmendrakariya . Also there is something else I changed in the Dockerfile that you may like, now there is no need to install gcc as I built the whl for the "problematic" safe_pysha3 package and put it in a repo. Tell me what do you think about it (or if you prefer the other way building the package locally).

Its all good! we can go ahead with the current approach!

**Pull request merged**
