### PR TITLE
Aave v3 liquidation call

### PR DESCRIPTION
**Pull request by nledo**

### CODE REVIEW

**Comment by nledo** [comment]
Guys, I'm getting the following error:

Run cat /tmp/rr_fork_node_log.txt
cat: /tmp/rr_fork_node_log.txt: No such file or directory
Error: Process completed with exit code 1.

I ignore the reason why...

**Comment by sanekto** [comment]
Hey, the error on the rr_fork_node_log is some leftovers from the hardhat implementation. It fails but the pipeline does not fail because of it, it fails because the tests fails. Anyway I've opened #101 to fix it and I also cherry picket that commit in this branch.

**Comment by nledo** [comment]
Thanks San! Didn't see the error... They are fixed now!

**Comment by sanekto** [comment]
Ok the failing tests are from lido, unrelated to this PR.

**Pull request merged**
